// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOffkaUy7hZrr8c3mFlYYgD-LBuSzvmDs',
    appId: '1:116775778142:web:9ec6a8fbd0b71f4103c1cf',
    messagingSenderId: '116775778142',
    projectId: 'garage-template',
    authDomain: 'garage-template.firebaseapp.com',
    storageBucket: 'garage-template.appspot.com',
    measurementId: 'G-Y804FJQV9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrO64FWPPx1hDLlcLC2BhkkCK9Ch7ebSY',
    appId: '1:116775778142:android:f8acdc52690fcf8303c1cf',
    messagingSenderId: '116775778142',
    projectId: 'garage-template',
    storageBucket: 'garage-template.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS1QGwGjo5B71DpNYKnscdH6O9t63AIAM',
    appId: '1:116775778142:ios:88733302d02168a603c1cf',
    messagingSenderId: '116775778142',
    projectId: 'garage-template',
    storageBucket: 'garage-template.appspot.com',
    iosClientId: '116775778142-m2lk81t3r4ul4jpmevs50o7c9p3i090s.apps.googleusercontent.com',
    iosBundleId: 'com.example.authCrudMapTemplate',
  );
}
